import { Montserrat } from "next/font/google";
import {Boogaloo} from 'next/font/google'
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});

const boogaloo = Boogaloo({
  variable: "--font-boogaloo",
  subsets: ["latin"],
  weight: ["400"], 
});

export const metadata = {
  title: "artbeat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.variable} ${boogaloo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
